# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/YOUR_GITHUB_REPO.git'
            }
        }

        stage('Compile Java Program') {
            steps {
                sh 'javac src/HelloWorld.java'
            }
        }

        stage('Run Java Program') {
            steps {
                sh 'java -cp src HelloWorld'
            }
        }

        stage('Print Output') {
            steps {
                script {
                    def output = sh(script: 'java -cp src HelloWorld', returnStdout: true).trim()
                    echo "Program Output: ${output}"
                }
            }
        }
    }
}

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
